FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY index.css /usr/share/nginx/html/index.css
COPY index.js /usr/share/nginx/html/index.js
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
